version: 2
jobs:
    build:
      docker:
      - image: larse514/circleci-java-agent:latest
      environment:
        IMAGE: larse514/circleci-java-agent
      steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build && Test
          command: |
              make IMAGE="${IMAGE}" TAG="${CIRCLE_BUILD_NUM}"
      - run:
          name: Deploy
          command: |
              make release TAG="${CIRCLE_BUILD_NUM}"